In [ ]:
1)Creating 5*5 array no of elements & length of an array

In [11]:
import numpy as np

# Create a 5x5 matrix in integer
x = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])
print("The Value of xis:",x)
print("The Shape of xis:",x.shape)
print("The Size of x is:",x.size)
print("THe length of the x is:",len(x))
print(x[0,4])
print(x[2,3])
print(x[3,2])
print(x[1,2])
print(x[4,3])
print(x[2,4])
print(x[4,4])
print(x[3,4])
print(x[2,2])


The Value of xis: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The Shape of xis: (5, 5)
The Size of x is: 25
THe length of the x is: 5
5
14
18
8
24
15
25
20
13


In [9]:
# Create a 5x5 matrix in float
x = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]],dtype = float)
print("The Value of xis:",x)
print("The Shape of xis:",x.shape)
print("The Size of x is:",x.size)
print("THe length of the x is:",len(x))


The Value of xis: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
The Shape of xis: (5, 5)
The Size of x is: 25
THe length of the x is: 5
5.0
14.0
18.0
8.0
24.0
15.0
25.0
20.0
13.0


In [ ]:
#2)acessing the elements by using row and coulmns with the helo of indexex

In [8]:
x = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]],dtype = float)

print(x[0,4])
print(x[2,3])
print(x[3,2])
print(x[1,2])
print(x[4,3])
print(x[2,4])
print(x[4,4])
print(x[3,4])
print(x[2,2])



5.0
14.0
18.0
8.0
24.0
15.0
25.0
20.0
13.0


In [ ]:
3)Creating the 3 d array and acessing the elemnts from 3d array

In [23]:
x = np.array([[[12,23,55,90],[12,45,67,65]],  
                [[13,11,55,75],[46,22,78,90]],
                [[76,20,27,67],[89,22,43,47]],
                [[24,90,92,68],[81,32,30,86]]])
print(x[1,0,2])
print(x[2,1,1])
print(x[3,0,2])
print(x[3,1,2])
print(x[0,1,1])
print(x[2,1,2])
print(x[3,1,3])
print(x[1,1,2])
print(x[2,1,0])
print(x[1,1,1])


55
22
92
30
45
43
86
78
89
22


In [26]:
x = np.array([[[12,23,55,90],[12,45,67,65],[12,13,14,15]],  
                [[13,11,55,75],[46,22,78,90],[45,57,68,45]],
                [[76,20,27,67],[89,22,43,47],[13,23,34,45]],
                [[24,90,92,68],[81,32,30,86],[45,56,78,90]]])
print(x[3,2,3])
print(x[3,2,2])
print(x[0,2,1])
print(x[2,2,2])


90
78
13
34


In [31]:
#Slicing the elements
print(x[:,-1,:])
print(x[:,:,0])
print(x[:,:,:])


[[12 13 14 15]
 [45 57 68 45]
 [13 23 34 45]
 [45 56 78 90]]
[[12 12 12]
 [13 46 45]
 [76 89 13]
 [24 81 45]]
[[[12 23 55 90]
  [12 45 67 65]
  [12 13 14 15]]

 [[13 11 55 75]
  [46 22 78 90]
  [45 57 68 45]]

 [[76 20 27 67]
  [89 22 43 47]
  [13 23 34 45]]

 [[24 90 92 68]
  [81 32 30 86]
  [45 56 78 90]]]


In [ ]:
4)Creating an array with 120 elements

In [41]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])
y= x.reshape(10,12)   #in 2d array

print(y)
z = x.reshape(2,5,12)
print(z)   #in 3d array


[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [ 13  14  15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36]
 [ 37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72]
 [ 73  74  75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116 117 118 119 120]]
[[[  1   2   3   4   5   6   7   8   9  10  11  12]
  [ 13  14  15  16  17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32  33  34  35  36]
  [ 37  38  39  40  41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80  81  82  83  84]
  [ 85  86  87  88  89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104 105 106 107 108]
  [109 110 111 112 

In [ ]:
#single array to 3d  array

In [44]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])

y = x.reshape(5,4,6)
print(y)
z = x.reshape(2,5,12)
print(z)
s = x.reshape(3,2,20)
print(s)

[[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]]

 [[ 25  26  27  28  29  30]
  [ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]]

 [[ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]
  [ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]]

 [[ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]
  [ 91  92  93  94  95  96]]

 [[ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]
[[[  1   2   3   4   5   6   7   8   9  10  11  12]
  [ 13  14  15  16  17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32  33  34  35  36]
  [ 37  38  39  40  41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80  81  82  83  84]
  [ 85  86  87  88  89  90  91  92  93  94  95  96]
  [ 97  98  